### ISSUE TITLE
colons in image names cause trouble

### ISSUE THREAD

**Issue by paleozogt** [avirshup/DockerMake#35]
Given this DockerMake.yml:
```
"foo:bar":
    FROM: ubuntu:trusty

"foo:bar:baz":
    FROM: ubuntu:trusty
```

Running `docker-make 'foo:bar'` will work.

However, running `docker-make 'foo:bar:baz'` produces
```
docker-make 'foo:bar:baz'
Working directory: /home/sensory/Development/test/docker_make
Copy cache directory: /tmp
READING DockerMake.yml

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
       STARTING BUILD for "foo:bar:baz" (image definition "foo:bar:baz" from ./DockerMake.yml)

 * Building foo:bar:baz, Step 1/1:
     Image definition "foo:bar:baz" from file ./DockerMake.yml
  ----------------------------------------------------------------------------------------------   dmkbuild_foo:bar:baz_1: BUILD LOG   ----------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/docker-make", line 9, in <module>
    load_entry_point('DockerMake==0.5.6', 'console_scripts', 'docker-make')()
  File "/usr/local/lib/python2.7/dist-packages/dockermake/__main__.py", line 64, in main
    built, warnings = utils.build_targets(args, defs, targets)
  File "/usr/local/lib/python2.7/dist-packages/dockermake/utils.py", line 116, in build_targets
    pull=args.pull)
  File "/usr/local/lib/python2.7/dist-packages/dockermake/builds.py", line 98, in build
    step.build(client, usecache=usecache)
  File "/usr/local/lib/python2.7/dist-packages/dockermake/step.py", line 93, in build
    utils.stream_docker_logs(stream, self.buildname)
  File "/usr/local/lib/python2.7/dist-packages/dockermake/utils.py", line 186, in stream_docker_logs
    for item in stream:
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 311, in _stream_helper
    yield self._result(response, json=decode)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 226, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 222, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("invalid reference format")
```

**Comment by avirshup** [comment]
Hi @paleozogt - I actually wasn't aware that it's ever possible to use multiple colons in a name - does this work in other contexts? E.g., when I try just using the CLI tools, I get
```bash
$ docker tag imagename foo:bar:baz
Error parsing reference: "foo:bar:baz" is not a valid repository/tag: invalid reference format
```

**Comment by paleozogt** [comment]
Gah, sorry.  I should have checked that first.

**Comment by avirshup** [comment]
No worries, I appreciate you taking the time to create the issue in any case!
