### ISSUE TITLE
BuildError on termcolor - TypeError: unicode argument expected, got 'str'

### ISSUE THREAD

**Issue by epcim** [avirshup/DockerMake#46]
Got an issue on ubuntu bionic - not yet investigated...

It's just related to printing an red colored "error" output,   `E: Unable to locate package vi `.  When I fixed the name of the package to vim - it finished the build without any issues.

```
docker-make -f test-dockermake2.yaml build-image
Working directory: /home/pmichalec/hg2g/workspace-docker
Copy cache directory: /tmp
READING test-dockermake2.yaml

=============================================================================================================================================================================
                                       STARTING BUILD for "build-image" (image definition "build-image" from ./test-dockermake2.yaml)

* Step 1/2 for image build-image
  Building step baseimage defined in ./test-dockermake2.yaml
  ----------------------------------------------------------------   dmkbuild_build-image_1: BUILD LOG   ----------------------------------------------------------------
  Step 1/1 : FROM python:3.6-slim
  3.6-slim: Pulling from library/python
  c4bb02b17bb4: Pulling fs layer
  6d9a50844d9d: Pulling fs layer
  fd9974f38d04: Pulling fs layer
  4b23af621dd8: Pulling fs layer
  767ba56e1368: Pulling fs layer
  4b23af621dd8: Waiting
  767ba56e1368: Waiting
  6d9a50844d9d: Downloading (2.7MiB)
  c4bb02b17bb4: Downloading (28.7MiB)
  fd9974f38d04: Downloading (18.9MiB)
  6d9a50844d9d: Verifying Checksum
  6d9a50844d9d: Download complete
  4b23af621dd8: Downloading (240.0B)
  4b23af621dd8: Verifying Checksum
  4b23af621dd8: Download complete
  767ba56e1368: Downloading (1.9MiB)
  767ba56e1368: Verifying Checksum
  767ba56e1368: Download complete
  fd9974f38d04: Verifying Checksum
  fd9974f38d04: Download complete
  c4bb02b17bb4: Verifying Checksum
  c4bb02b17bb4: Download complete
  c4bb02b17bb4: Extracting
  c4bb02b17bb4: Pull complete
  6d9a50844d9d: Extracting
  6d9a50844d9d: Pull complete
  fd9974f38d04: Extracting
  fd9974f38d04: Pull complete
  4b23af621dd8: Extracting
  4b23af621dd8: Pull complete
  767ba56e1368: Extracting
  767ba56e1368: Pull complete
  {u'status': u'Digest: sha256:33a5a60a9a155f05ce10ad4a35fc4628a5209200cf024d040de02acb0b14360b'}
  {u'status': u'Status: Downloaded newer image for python:3.6-slim'}
  ---> dc41c0491c65
  Successfully built dc41c0491c65
  Successfully tagged dmkbuild_build-image_1:latest
  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------
* Created intermediate image dmkbuild_build-image_1

* Step 2/2 for image build-image
  Building step build-image defined in ./test-dockermake2.yaml
  ----------------------------------------------------------------   dmkbuild_build-image_2: BUILD LOG   ----------------------------------------------------------------
  Step 1/3 : FROM dmkbuild_build-image_1
  ---> dc41c0491c65
  Step 2/3 : RUN apt-get update  && apt-get install -y gcc vi
  ---> Running in 5f3b270d9a12
  Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
  Get:2 http://security.debian.org jessie/updates/main amd64 Packages [608 kB]
  Ign http://deb.debian.org jessie InRelease
  Get:3 http://deb.debian.org jessie-updates InRelease [145 kB]
  Get:4 http://deb.debian.org jessie Release.gpg [2434 B]
  Get:5 http://deb.debian.org jessie Release [148 kB]
  Get:6 http://deb.debian.org jessie-updates/main amd64 Packages [23.1 kB]
  Get:7 http://deb.debian.org jessie/main amd64 Packages [9064 kB]
  Fetched 10.1 MB in 8s (1185 kB/s) Reading package lists...
  Reading package lists...
  Building dependency tree...
  Reading state information...
  E: Unable to locate package vi 
Traceback (most recent call last):
  File "/usr/local/bin/docker-make", line 11, in <module>
    load_entry_point('DockerMake==0.6.0', 'console_scripts', 'docker-make')()
  File "/usr/local/lib/python2.7/dist-packages/dockermake/__main__.py", line 38, in main
    run(args)
  File "/usr/local/lib/python2.7/dist-packages/dockermake/__main__.py", line 88, in run
    built, warnings = utils.build_targets(args, defs, targets)
  File "/usr/local/lib/python2.7/dist-packages/dockermake/utils.py", line 128, in build_targets
    pull=args.pull)
  File "/usr/local/lib/python2.7/dist-packages/dockermake/builds.py", line 103, in build
    step.build(client, usecache=usecache)
  File "/usr/local/lib/python2.7/dist-packages/dockermake/step.py", line 151, in build
    raise errors.BuildError(dockerfile, str(e), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dockermake/errors.py", line 88, in __init__
    cprint('Docker build failure', 'red', attrs=['bold'], file=stream)
  File "/usr/local/lib/python2.7/dist-packages/termcolor.py", line 124, in cprint
    print((colored(text, color, on_color, attrs)), **kwargs)
TypeError: unicode argument expected, got 'str'


➜  workspace-docker python --version 
Python 2.7.14+


➜  workspace-docker docker-make --version
docker-make version 0.6.1a3


➜  workspace-docker cat test-dockermake2.yaml 
baseimage:
   FROM: python:3.6-slim

build-image:
   requires:
     - baseimage
   build: |
     RUN apt-get update \
      && apt-get install -y gcc vi
     ENV editor=vi
```

**Comment by avirshup** [comment]
I've fixed one manifestation of this issue, please LMK if it pops up again.
