### ISSUE TITLE
Update readme how --requires and --name should be used

### ISSUE THREAD

**Issue by epcim** [avirshup/DockerMake#48]
Hi, I have quite problem to simply figure out hou --requires and --name should be used on the CLI.
I want to add additional require to the target specified in  DockerMake.yml. When --name is not specified it fails, if it's specified as any other target in DockerMake it fails and if it's not defined it fails as well.

```
docker-make -f DockerMake.yml --requires salt -t ubuntu-xenial-salt-stable debian-stretch                                  
Working directory: /home/pmichalec/hg2g/workspace-salt/docker-salt-formulas.develop
Copy cache directory: /tmp
READING DockerMake.yml
Traceback (most recent call last):
  File "/usr/local/bin/docker-make", line 11, in <module>
    load_entry_point('DockerMake==0.6.0', 'console_scripts', 'docker-make')()
  File "/usr/local/lib/python3.6/dist-packages/dockermake/__main__.py", line 38, in main
    run(args)
  File "/usr/local/lib/python3.6/dist-packages/dockermake/__main__.py", line 81, in run
    targets = utils.get_build_targets(args, defs)
  File "/usr/local/lib/python3.6/dist-packages/dockermake/utils.py", line 75, in get_build_targets
    assert args.requires and args.name
AssertionError
➜  docker-salt-formulas.develop git:(develop) ✗ docker-make -f DockerMake.yml --requires salt --name zzz -t ubuntu-xenial-salt-stable debian-stretch
Working directory: /home/pmichalec/hg2g/workspace-salt/docker-salt-formulas.develop
Copy cache directory: /tmp
READING DockerMake.yml
FATAL ERROR: No base image found in zzz's dependencies
➜  docker-salt-formulas.develop git:(develop) ✗ docker-make -f DockerMake.yml --requires salt --name debian-stretch -t ubuntu-xenial-salt-stable debian-stretch
Working directory: /home/pmichalec/hg2g/workspace-salt/docker-salt-formulas.develop
Copy cache directory: /tmp
READING DockerMake.yml
Traceback (most recent call last):
  File "/usr/local/bin/docker-make", line 11, in <module>
    load_entry_point('DockerMake==0.6.0', 'console_scripts', 'docker-make')()
  File "/usr/local/lib/python3.6/dist-packages/dockermake/__main__.py", line 38, in main
    run(args)
  File "/usr/local/lib/python3.6/dist-packages/dockermake/__main__.py", line 81, in run
    targets = utils.get_build_targets(args, defs)
  File "/usr/local/lib/python3.6/dist-packages/dockermake/utils.py", line 76, in get_build_targets
    assert args.name not in defs.ymldefs
AssertionError
➜  docker-salt-formulas.develop git:(develop) ✗ docker-make -f DockerMake.yml --requires salt --name debian -t ubuntu-xenial-salt-stable debian-stretch 
Working directory: /home/pmichalec/hg2g/workspace-salt/docker-salt-formulas.develop
Copy cache directory: /tmp
READING DockerMake.yml
FATAL ERROR: No base image found in debian's dependencies
➜  docker-salt-formulas.develop git:(develop) ✗ docker-make -f DockerMake.yml --requires salt --name wheelhouse -t ubuntu-xenial-salt-stable debian-stretch
Working directory: /home/pmichalec/hg2g/workspace-salt/docker-salt-formulas.develop
Copy cache directory: /tmp
READING DockerMake.yml
Traceback (most recent call last):
  File "/usr/local/bin/docker-make", line 11, in <module>
    load_entry_point('DockerMake==0.6.0', 'console_scripts', 'docker-make')()
  File "/usr/local/lib/python3.6/dist-packages/dockermake/__main__.py", line 38, in main
    run(args)
  File "/usr/local/lib/python3.6/dist-packages/dockermake/__main__.py", line 81, in run
    targets = utils.get_build_targets(args, defs)
  File "/usr/local/lib/python3.6/dist-packages/dockermake/utils.py", line 76, in get_build_targets
    assert args.name not in defs.ymldefs
AssertionError
```

**Comment by epcim** [comment]
```docker-make -f DockerMake.yml --requires ubuntu-bionic salt -t ubuntu-xenial-salt-stable --name xxx    ```
my fault, this way it works.
