### ISSUE TITLE
Is Python 2.7 Supported?

### ISSUE THREAD

**Issue by MarkRoddy** [avirshup/DockerMake#62]
Per the README:
```
Requires Docker and Python 2.7 or 3.5+.
```

However, after a pip install on Python 2.7 (system Python via Ubuntu 16.04,):
```
$ docker-make --list
Traceback (most recent call last):
  File "/usr/local/bin/docker-make", line 7, in <module>
    from dockermake.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/dockermake/__main__.py", line 23, in <module>
    from . import cli, utils, staging
  File "/usr/local/lib/python2.7/dist-packages/dockermake/utils.py", line 24, in <module>
    from . import errors
  File "/usr/local/lib/python2.7/dist-packages/dockermake/errors.py", line 90
    print(dockerfile, file=dff)
                          ^
SyntaxError: invalid syntax
```

I noticed that metafiles (`setup.py`, `codeship-*.yml`, etc) only reference Python 3.x, and I wanted to confirm that 2.7 is officially supported before digging deeper into this problem.

**Comment by MarkRoddy** [comment]
I'm seeing syntax errors under a Python 3.5 installation (stock Ubuntu too) as well:

```
$ docker-make --list
Traceback (most recent call last):
  File "/usr/local/bin/docker-make", line 7, in <module>
    from dockermake.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/dockermake/__main__.py", line 24, in <module>
    from .imagedefs import ImageDefs
  File "/usr/local/lib/python3.5/dist-packages/dockermake/imagedefs.py", line 167
    **kwargs,
            ^
SyntaxError: invalid syntax
```

I can provide additional details if that helps.
